name: copernicus-climate
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - ipykernel
  - nb_conda_kernels
  - jupyter
  - rasterstats
  - geopandas
  - xarray
  - rasterio
  - shapely
  - matplotlib
  # - pysqlite2
